apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  selector:
    matchLabels:
      app: demo
  replicas: 4    
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - image: darshannraval/mytest:tagVersion
        name: mytest
        ports:
        - containerPort: 80
          protocol: TCP
      imagePullSecrets:
        - name: my-secret      
